CREATE EXTENSION IF NOT EXISTS citext;
CREATE TABLE IF NOT EXISTS users (nickname CITEXT UNIQUE NOT NULL PRIMARY KEY, fullname varchar(128) NOT NULL,
about text, email CITEXT UNIQUE NOT NULL); CREATE UNIQUE INDEX ON users (nickname);

